"""
Complete test of itinerary generation with Airflow database venues.
Demonstrates that venues from the DB are used in the generated itinerary.
"""
import asyncio
import json
import sys
import os
from datetime import datetime, timedelta

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(__file__)), 'backend'))

from services.itinerary_service import ItineraryService
from utils.id_generator import generate_trip_id

async def test_itinerary_with_venues():
    """Generate itinerary and verify venues come from database."""
    
    print("="*80)
    print("ITINERARY GENERATION TEST WITH AIRFLOW VENUE DATABASE")
    print("="*80)
    print()
    
    # Sample trip preferences (all required fields)
    preferences = {
        # Location
        "city": "Toronto",
        "country": "Canada",
        "location_preference": "downtown",
        
        # Dates (3-day trip)
        "start_date": "2026-03-15",
        "end_date": "2026-03-17",
        "duration_days": 3,
        
        # Budget
        "budget": 900.0,  # $300/day for Toronto
        "budget_currency": "CAD",
        
        # Preferences
        "interests": ["Culture and History", "Food and Beverage"],
        "pace": "moderate",
        
        # Optional fields
        "starting_location": "Downtown Toronto",
        "hours_per_day": 8,
        "transportation_modes": ["transit", "walking"],
    }
    
    print("📋 Trip Preferences:")
    print(f"   Destination: {preferences['city']}, {preferences['country']}")
    print(f"   Dates: {preferences['start_date']} to {preferences['end_date']}")
    print(f"   Duration: {preferences['duration_days']} days")
    print(f"   Budget: ${preferences['budget']} {preferences['budget_currency']} (${preferences['budget']/preferences['duration_days']:.2f}/day)")
    print(f"   Interests: {', '.join(preferences['interests'])}")
    print(f"   Pace: {preferences['pace']}")
    print()
    
    # Initialize service
    print("🔧 Initializing ItineraryService...")
    service = ItineraryService()
    request_id = generate_trip_id()
    print(f"   Request ID: {request_id}")
    print()
    
    # Generate itinerary
    print("🚀 Generating itinerary (this may take 10-20 seconds)...")
    print()
    
    try:
        itinerary = await service.generate_itinerary(
            preferences=preferences,
            request_id=request_id
        )
        
        print("✅ Itinerary generated successfully!")
        print()
        print("="*80)
        print("ITINERARY DETAILS")
        print("="*80)
        print()
        
        # Summary
        print(f"Trip ID: {itinerary.trip_id}")
        print(f"Total Cost: ${itinerary.total_spent:.2f} CAD")
        print(f"Activities per Day (avg): {itinerary.activities_per_day_avg:.1f}")
        print(f"Total Travel Time: {itinerary.total_travel_time_hours:.1f} hours")
        print(f"Number of Days: {len(itinerary.days)}")
        print()
        
        # Count activities from database
        total_activities = 0
        db_activities = 0
        
        for day in itinerary.days:
            total_activities += len(day.activities)
            db_activities += sum(1 for a in day.activities if a.from_database)
        
        print("📊 DATABASE VENUE USAGE:")
        print(f"   Total activities: {total_activities}")
        print(f"   From database: {db_activities}")
        print(f"   Generated by AI: {total_activities - db_activities}")
        if total_activities > 0:
            print(f"   Database coverage: {(db_activities/total_activities*100):.1f}%")
        print()
        
        # Day-by-day breakdown
        for day in itinerary.days:
            print("="*80)
            print(f"DAY {day.day_number} - {day.date}")
            print("="*80)
            print()
            
            # Morning departure
            if day.morning_departure:
                print(f"🚗 Morning Departure:")
                print(f"   From: {day.morning_departure.from_location}")
                print(f"   To: {day.morning_departure.to_location}")
                print(f"   Duration: {day.morning_departure.duration_minutes} min ({day.morning_departure.mode})")
                print()
            
            # Activities
            print(f"🎯 Activities ({len(day.activities)}):")
            for i, activity in enumerate(day.activities, 1):
                db_flag = "🗄️  [DB]" if activity.from_database else "🤖 [AI]"
                print(f"\n   {i}. {db_flag} {activity.venue_name}")
                print(f"      Time: {activity.planned_start} - {activity.planned_end}")
                print(f"      Category: {activity.category or 'N/A'}")
                print(f"      Cost: ${activity.estimated_cost:.2f}")
                if activity.notes:
                    print(f"      Notes: {activity.notes}")
                if activity.duration_reason:
                    print(f"      Duration: {activity.duration_reason}")
            
            print()
            
            # Meals
            print(f"🍽️  Meals ({len(day.meals)}):")
            for meal in day.meals:
                print(f"   - {meal.meal_type.title()} at {meal.venue_name} ({meal.planned_time}) - ${meal.estimated_cost:.2f}")
            
            print()
            
            # Evening return
            if day.evening_return:
                print(f"🏠 Evening Return:")
                print(f"   From: {day.evening_return.from_location}")
                print(f"   To: {day.evening_return.to_location}")
                print(f"   Duration: {day.evening_return.duration_minutes} min ({day.evening_return.mode})")
            
            print()
            print(f"💰 Budget: ${day.daily_budget_spent:.2f} / ${day.daily_budget_allocated:.2f}")
            print()
        
        # Save to file
        output_file = f"itinerary_trip_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        with open(output_file, 'w') as f:
            json.dump(itinerary.to_dict(), f, indent=2)
        
        print("="*80)
        print(f"✅ Itinerary saved to: {output_file}")
        print("="*80)
        
        # Verification summary
        print()
        print("🔍 VERIFICATION CHECKLIST:")
        checks = [
            ("Days match duration", len(itinerary.days) == preferences['duration_days']),
            ("Budget within limits", itinerary.total_spent <= preferences['budget']),
            ("Activities per day > 0", all(len(d.activities) > 0 for d in itinerary.days)),
            ("All days have meals", all(len(d.meals) >= 2 for d in itinerary.days)),
            ("DB venues used", db_activities > 0),
            ("Interests covered", len(itinerary.days) > 0),
        ]
        
        for check_name, passed in checks:
            status = "✅" if passed else "❌"
            print(f"   {status} {check_name}")
        
        print()
        
        return itinerary
        
    except Exception as e:
        print(f"❌ Error generating itinerary: {e}")
        import traceback
        traceback.print_exc()
        return None

if __name__ == "__main__":
    asyncio.run(test_itinerary_with_venues())
